my:
  greetings: http://localhost:8080/insurance-service/getAllPlans 
  list:
     values: One, Two, Three
db:
  connection:  Update connection-string-here-from-config-client micro serice
  host: 127.0.0.1
  port: 1700  
