my:
  greetings: new new Newly Updated Hello World from config client micro service 
  list:
     values: One, Two, Three
db:
  connection: connection-string-here-from-config-client micro serice
  host: 127.0.0.1
  port: 1300
client:
     insurance:
             url=/insurance-service/getAllPlans  
